services:
  tx-counter:
    build: 
      context: ./HyperSync
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    restart: always
  
  backend:
    build: 
      context: ./MonadDashboard
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    restart: always
    depends_on:
      - tx-counter
